# Generated by Django 4.0.1 on 2022-01-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.CharField(choices=[('urgente', 'Urgente'), ('importante', 'Importante'), ('precisa ser feito', 'Precisa ser feito')], default='importante', max_length=30)),
                ('status', models.CharField(choices=[('concluído', 'Concluído'), ('pendente', 'Pendente'), ('adiado', 'Adiado')], default='pendente', max_length=30)),
            ],
        ),
    ]
