# Generated by Django 4.0.1 on 2022-01-15 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('concluída', 'Concluída'), ('ativa', 'Ativa')], default='pendente', max_length=30),
        ),
    ]
