# Generated by Django 4.0.1 on 2022-01-15 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_alter_tarefa_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='due_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='task',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='description',
            field=models.TextField(),
        ),
    ]
