# Generated by Django 4.0.1 on 2022-01-15 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0003_tarefa_due_date_tarefa_task_alter_tarefa_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarefa',
            old_name='task',
            new_name='titulo',
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='due_date',
            field=models.DateField(default=''),
        ),
    ]
