# Generated by Django 4.0.1 on 2022-01-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0004_rename_task_tarefa_titulo_alter_tarefa_due_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='due_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('concluida', 'Concluida'), ('ativa', 'Ativa')], default='ativa', max_length=30),
        ),
    ]
