# Generated by Django 4.0.1 on 2022-01-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0005_group_alter_tarefa_description_alter_tarefa_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='grupo',
            field=models.CharField(default='', max_length=200),
        ),
    ]
