# Generated by Django 4.0.1 on 2022-01-30 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0006_tarefa_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='categorie',
            field=models.CharField(default='importante', max_length=100),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(default='ativa', max_length=200),
        ),
    ]
