# Generated by Django 4.0.1 on 2022-01-30 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0007_alter_tarefa_categorie_alter_tarefa_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='due_date',
        ),
    ]
