# Generated by Django 4.0.1 on 2022-01-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0008_remove_tarefa_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='grupo',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
